version: "2"
services:
  app:
    container_name: user_crud
    restart: on-failure
    image: user_crud
    ports:
      - "8000:8000"
    working_dir: /app
    environment:
      MYSQL_USER: "root"
      MYSQL_PASSWORD: 
      MYSQL_DB: "test"
  db:
    container_name: mysql
    image: mysql:5.7
    restart: always
    volumes:
      - ./sqls:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE="test"
      - MYSQL_USER="root"
      - MYSQL_PASSWORD=""
    ports:
      - 3306:3306
  cache:
    container_name: redis
    image: redis
    restart: always
    ports:
      - 6379:6379
    